image:
  repository: lohitha12100706/clinic-scheduler
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 4200
  targetPort: 3002

ingress:
  enabled: false

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

replicaCount: 1