image:
  repository: lohitha12100706/clinic-scheduler
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 4200
  targetPort: 4200

ingress:
  enabled: false

resources:
  limits:
    cpu: 2000m
    memory: 2Gi
  requests:
    cpu: 1000m
    memory: 1Gi

replicaCount: 1