apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "clinic-scheduler.fullname" . }}
  labels:
    app: {{ include "clinic-scheduler.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "clinic-scheduler.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "clinic-scheduler.name" . }}
    spec:
      automountServiceAccountToken: false
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: DB_HOST
          value: postgres
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: clinic
        - name: DB_USER
          value: postgres
        - name: DB_PASSWORD
          value: admin
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}